### PR TITLE
Added platform-independent CAS path in threading.h

### PR DESCRIPTION
**Pull request by StephenDenham-districtm**
- This is necessary to support ARM builds
- Existing path is unaltered for x86 builds

### CODE REVIEW

**Comment by Piotr-51Degrees** [comment]
Hi @StephenDenham-districtm! 

Thank you for your input - it is much appreciated especially that it adds support for an additional platform.

We will review the PR and create an ARM testing environment to fully test the changes. Unfortunately we are quite busy at the moment so I cannot provide a definitive time frame for this to happen but will keep you posted on any news in that matter.

Thank you again, 
Piotr

**Comment by StephenDenham-districtm** [comment]
Thanks Piotr for the update!

FYI we have attempted to try fork the dependency chain with submodules up to device-detection-java so we could test this for ourselves however we hit several issues (the latest of which was authenticating with `oss.sonatype.org`)

**Comment by Piotr-51Degrees** [comment]
I am really sorry to hear that you have had issues with dependency chain. I will schedule some time to investigate this but again, at the moment, unfortunately, I cannot give you a definitive time frame for this. Have you been successful with any other language/API?

Thanks,
Piotr

**Comment by StephenDenham-districtm** [comment]
Hi Piotr, just to get back to you on your question regarding other language/APIs, I'm not sure I fully understand your question but perhaps I can give more context...

- We ported our application (Scala) to support Arm/Graviton2 but are hitting a runtime error from our 51degrees dependency, which is traced back through `device-detection-java` to `common-cxx`
- Due to our low latency requirements, moving this out into a separate service isn't a viable option.
- This PR should resolve that issue while not altering any existing behavior
- To leverage this change, we can not fork everything in the chain as there are other dependencies to replicate the downstream build-processes, including requiring an account with Nexus Sonatype
- We do not have a use-case for any other languages so have not investigated those

**Comment by jwrosewell** [comment]
I have labelled as an enhancement for scheduling in June.

In addition to reviewing the code for the PR we also need to modify the [CI scripts](https://github.com/51Degrees/common-cxx/tree/master/ci) to automatically test the ARM configuration to enable this to be added as a [supported version](http://51degrees.com/documentation/4.2/_info__version_support.html) for compiling from source code. This will also involve being more explicit about ARM, Intel, and other specific architectures on the version page.

@StephenDenham-districtm do you have any tests you would like to see included in the CI beyond those that are already present?

Is everyone one comfortable addressing the release to Maven / Sonatype as a pre-compiled package after this PR has been reviewed and merged to main with any tests / CI changes?

**Comment by StephenDenham-districtm** [comment]
That's fantastic news! Thank you

> we also need to modify the CI scripts

Can I ask what CI platform are you leveraging? It wasn't clear just looking at the yaml but would be happy to take a look with some direction.

> @StephenDenham-districtm do you have any tests you would like to see included in the CI beyond those that are already present?

We don't have any tests to add unfortunately. We did not look at those but to be transparent, we're not really a C/C++ shop here.

> Is everyone one comfortable addressing the release to Maven / Sonatype as a pre-compiled package after this PR has been reviewed and merged to main with any tests / CI changes?

I presume the question regarding Maven is addressed to owners of downstream dependencies such as device-detection-java? If needed we can submit additional PRs to those repos after any release here

**Comment by ben51degrees** [comment]
Hi @StephenDenham-districtm ,
The CI platform we use is Azure DevOps. It's worth noting that we've recently made a lot of changes to the YAML which is now in the master branch.

In terms of tests, if there's nothing specific you feel needs adding to cover this change, I'm happy that the existing tests are sufficient provided that we add an ARM agent to the CI.

I car start this week on adding ARM to our CI, then update when I have results from the testing.

On your question about PRs for Maven, that will be handled as part of our twice monthly releases. So if there is a change included in the release for this repo, the team will also test and include this in any repos/packages which depend on this. One change which we will need to make to the Maven package is that ARM binaries will need to be compiled and inlcluded. The YAML for this is [here](https://github.com/51Degrees/device-detection-java/blob/master/build-and-publish.yml) and currently builds binaries for x86 and x86-x64. I'm expecting this change to be fairly trivial, but if there are any quirks of ARM you've run into compiling the binaries, any info would be appreciated.

Thanks,
Ben.

**Comment by jwrosewell** [comment]
We'll also need to consider different versions of ARM and 32bit. Double width interlocked compare and exchange operations are pretty low level. We need to be clear exactly what the scope for ARM support is in the threading.h/c files, repo, tests and public documentation.

**Comment by ben51degrees** [comment]
Hi @StephenDenham-districtm ,

On the CI integration:
After doing some more research into this, it seems Microsoft do not offer hosted ARM build agents, nor to they support it on Azure VMs which could be used as a self-hosted build agent. They have recently added support for self-hosted build agents on ARM, but have said that a [hosted image is not planned](https://github.com/microsoft/azure-pipelines-agent/issues/1911).
We have opened a service case with Microsoft to determine when this will be possible. Getting dedicated ARM hardware for continuous integration is not feasible at the moment given the small demand. So for now, we will not be adding continuous integration for ARM builds, however we will be adding smaller scale ARM hardware for development and manual testing in the meantime.

On the code side:
I've had to make some more changes to this in order to compile this project using CMake. It seems GCC does not define `__arm__`, but does define `__aarch64__`. There is also `libatomic` which needs linking when using GCC on ARM.
Could you give me a few extra details on your environment?
1. Which ARM processor are you using?
2. Is it 32 or 64 bit?
3. Which compiler are you using?
4. What's the OS?

Thanks,
Ben

**Comment by StephenDenham-districtm** [comment]
We really appreciate you diving into this! Apologies for the delayed response.

We are running on Amazon ECS-optimized Amazon Linux 2 AMI but are hoping to also be able to run on the Graviton2 64-bit equivalent. [This link](https://github.com/aws/aws-graviton-getting-started/blob/99df606f4eafb300a76280669cc04e9bc2eb27d2/c-c%2B%2B.md) should give more detail.
Given our application is Java based, our _ideal_ would be not to have to compile this ourselves (we have tested it but the dependency chain is difficult to us to reproduce on our end) but be able to pull an Arm-compatible `device-detection-java` library from a Maven repository.

Regarding Azure running Arm hardware for CI builds, I understand demand for that may be low. I don't know if a cross-compiler was an option available to you. That's at least how we've managed it for other systems like Docker images (`docker buildx build --platform linux/amd64,linux/arm64 ...`).

Thank you
Stephen

**Comment by ben51degrees** [comment]
Hi @StephenDenham-districtm ,

Thanks for the info on the hardware, that's helpful.

I completely agree, you shouldn't need to compile native files yourself for the Java module. Our current release includes native binaries for x86/x64, so the plan is to include arm and arm64 binaries in the same way.

With the CI builds, a cross-compiler will be exactly what we will be doing. Microsoft will not be supporting hosted ARM any time in the near future, so cross-compilation is definitely the way to go. We will be running tests on this before releasing, however there won't be testing built into the CI for arm due to it being cross-compiled.

I'll keep you updated with when you can expect the changes to be released.

Thanks,
Ben.

**Comment by StephenDenham-districtm** [comment]
Fantastic news. Our team are really excited to see this move forward. Thanks for the clarification regarding the CI builds. I see what you're saying that cross-platform tests won't be practical for now.

**Comment by ben51degrees** [comment]
Hi @StephenDenham-districtm ,

The preliminary work on this is complete now. I've found that as of GCC 5, using the `__atomic_*` buit-ins is perfered over the deprecated `__sync_*` built-ins, so we will be moving to that. Performance on x86 and x86_64 is unaffected, as the built-ins resolve to the same `cmpxchg` instructions anyway.
With arm and aarch64, the `__atomic_is_lock_free` function reports false, likely because `LL/SC` instructions are used along with a memory fence. Performance figures for arm are consistent with our earlier implementations, so we're happy that's not too much of an issue.
An extra benefit of using the `__atomic_*` built-ins is that if it does not resolve to an instruction, the compiler will fall back to a library function, which will be slower, but offer wider support.

The work for this, including this repo, device-detection-cxx, device-detection-java (and the associated Maven packages) is scheduled to finish on 23rd July, and will then be included in our release on 4th April.

Let me know if that timescale works for you. If not, we can always give you access to beta packages earlier.

**Comment by StephenDenham-districtm** [comment]
Thank you for the detailed update @ben51degrees, that is great news! The timeline certainly works for us. Access to beta packages would give us a head-start on testing but would see it as a nice-to-have

**Comment by StephenDenham-districtm** [comment]
Am I right to assume you mean 4th of August and not April?

**Comment by ben51degrees** [comment]
> 
> 
> Am I right to assume you mean 4th of August and not April?

Sorry, yes I did mean August. I'll edit that comment now.

**Comment by StephenDenham-districtm** [comment]
Hi @ben51degrees, just wanted to check in on this if we were still on track? We are planing our next couple sprints and wanted to know if this was ready for work on our side?
Thank you

**Comment by Automation51D** [comment]
Hi Stephen,
We are releasing our code next Wednesday and ARM is in that release (the documentation will follow a day or so later once we’ve updated all the repositories).

If you have any further questions, please let us know.

Thank you,
Paul


Best Regards
Paul Ackerman
Finance Director
+44 7769 687615

**Comment by StephenDenham-districtm** [comment]
Fantastic, thank you Paul!

**Comment by ben51degrees** [comment]
I'm closing this now as it's been included in [4.3.1](https://github.com/51Degrees/common-cxx/releases/tag/4.3.1)

**Comment by StephenDenham-districtm** [comment]
Perfect, thank you!

**Pull request closed without merging**
